4.0.0 release
OneSignal/OneSignal-Xamarin-SDK pull request #253
Opened 2021-11-18 23:37 UTC by tanaynigam

### WIP Xamarin OneSignal SDK Major Release 4.0.0

### Bindings
* iOS - Edited ApiDefinition to create Bindings from .aar file
* iOS - Updated Structs.cs for iOS native enums
* Android - Updated Project settings to use class parse instead of jar2xml as jar file parser
* Android - Updated Project settings to remove `Java.Interop` package

### OneSignal.Core
* Deleted files in OneSignal.Abstraction
* Renamed project and namespace to OneSignal.Abstraction to OneSignal.Core
* Added abstract partial class `OneSignalSDK` to OneSignal.Core
* Added enums LogType and LogoutOptions in OneSignal.Core
* Added Json and Laters helper classes

### OneSignal.Android
* Removed Additional classes from OneSignal.Android
* Added OneSignal Android implementation for OneSignal SDK abstract partial class
* Added Android callback classes that use Later
* Added helper class for conversion of Android native state to Xamarin states.
* Added AndroidX, Firebase messaging, and Kotlin related packages OneSignal.Android

### OneSignal.iOS
* Added OneSignal iOS implementation for OneSignal SDK abstract partial class
* Added iOS callback classes that use Later
* Added helper class for conversion of iOS native state to Xamarin states.

### Com.OneSignal
* Replaced the IOneSignal interface with OneSignalSDK abstract partial class

### Sample Apps
* Updated with new Apis

2021-11-19 19:10 UTC, jkasten2 requested changes
> Reviewed 23 of 69 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: 23 of 97 files reviewed, 3 unresolved discussions (waiting on @jkasten2 and @tanaynigam)

___
*[Com.OneSignal.Core/OneSignalSDK.cs, line 16 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MopZ-azEkgeyD4dCK8g:-MopZ-azEkgeyD4dCK8h:b-kvgzz4) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/OneSignalSDK.cs#L16)):*
> ```Smalltalk
> 
>             //// only 1 sdk should be available for any given supported platform
>             //var availableSDKs = ReflectionHelpers.FindAllAssignableTypes<OneSignal>("OneSignal");
> ```

Remove commented out code, `CreateOneSignal` in `OneSignal.cs` already handles this.
___
*[Com.OneSignal.Core/OneSignalSDK.cs, line 29 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mop_4U681xBjFBV6YiF:-Mop_4U681xBjFBV6YiG:bxbhws1) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/OneSignalSDK.cs#L29)):*
> ```Smalltalk
> 
>         #region Delegate Definitions
>         /// <summary>
> ```

Update signature and param to match Unity.
```
        /// <summary>
        /// When a push notification has been received and is about to be displayed
        /// </summary>
        /// <param name="notification">Details of the notification to be shown</param>
        /// <returns>The notification object or null if the notification should not be displayed</returns>
        public delegate Notification NotificationWillShowDelegate(Notification notification);
```
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/OneSignal.cs#L52-L57
___
*[Com.OneSignal.Core/Utilities/Later.cs, line 5 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MopT5SM6fcNjY1EaN2y:-MopT5SM6fcNjY1EaN2z:b-5us3vj) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/Utilities/Later.cs#L5)):*
> ```Smalltalk
> using System.Threading.Tasks;
> 
> namespace Laters {
> ```

This class is a bit different than Unity's. Recommend we pull in the exact file.
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/release/3.0.0-beta.1/com.onesignal.unity.ios/Runtime/Utilities/Later.cs


<!-- Sent from Reviewable.io -->

2021-11-19 20:34 UTC, jkasten2 requested changes
> Reviewed 24 of 35 files at r1, 13 of 69 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: 60 of 97 files reviewed, 12 unresolved discussions (waiting on @jkasten2 and @tanaynigam)

___
*[Com.OneSignal.Android/OneSignalImplementation.cs, line 78 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MottRj-DwkNEgaJoYiv:-MottRj-DwkNEgaJoYiw:bvu8bu9) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Android/OneSignalImplementation.cs#L78)):*
> ```Smalltalk
>       }
> 
>       public override async Task<bool> Logout(LogoutOptions options = LogoutOptions.Email | LogoutOptions.SMS | LogoutOptions.ExternalUserId
> ```

Unity 3.x.x split this up into different methods.
___
*[Com.OneSignal.Android/OneSignalImplementation.cs, line 142 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MottwsGBMCPtduHyXQ9:-MottwsGBMCPtduHyXQA:bvo1qmh) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Android/OneSignalImplementation.cs#L142)):*
> ```Smalltalk
>       }
> 
>       //public override async Task<bool> DeleteTags(ICollection<string> keys) {
> ```

Address commented out methods, we can use Unity's signatures and most of the code from there too.
___
*[Com.OneSignal.Core/OneSignalSDK.cs, line 8 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Motlbes8i-qlrs14LgS:-Motlbes8i-qlrs14LgT:bvlvg2e) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/OneSignalSDK.cs#L8)):*
> ```Smalltalk
> 
> namespace Com.OneSignal.Core {
>     public abstract partial class OneSignalSDK {
> ```

Most of the contents of this file can be pulled from Unity:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/OneSignal.cs#L37
___
*[Com.OneSignal.Core/OneSignalSDK.cs, line 141 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MotfnKU2VIyIpOQsdh9:-MoteV9A0iAwVqhpACKc:b-tkroxr) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/OneSignalSDK.cs#L141)):*
> ```Smalltalk
> 
> 
>         //public abstract void InitWithContext();
> ```

Remove `InitWithContext`from this public API file, we call this internally in the SDK.
___
*[Com.OneSignal.Core/OneSignalSDK.cs, line 156 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MotfHwx0EeJD85r1flZ:-MotfHwx0EeJD85r1fl_:bnuq3vc) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/OneSignalSDK.cs#L156)):*
> ```Smalltalk
>         //public abstract void SetLogLevel(LOG_LEVEL inLogCatLogLevel, LOG_LEVEL inVisualLogLevel);
> 
>         //public abstract Task<NotificationPermission> PromptForPushNotificationsWithUserResponse();
> ```

This needs to be included to prompt for iOS notifications, see Unity's definition:
```C#
        /// <summary>
        /// Prompt the user for notification permissions.
        /// </summary>
        /// <returns>Awaitable NotificationPermission which provides the user's consent status</returns>
        /// <remarks>Recommended: Do not use and instead follow
        /// <a href="https://documentation.onesignal.com/docs/ios-push-opt-in-prompt">Push Opt-In Prompt</a></remarks>
        public abstract Task<NotificationPermission> PromptForPushNotificationsWithUserResponse();
```
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/OneSignal.cs#L184-L190
___
*[Com.OneSignal.Core/PermissionState.cs, line 5 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MotmL_o3Xh29gCVZBz7:-MotmL_p-DKcQHhqRg-q:bc61wcm) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/PermissionState.cs#L5)):*
> ```Smalltalk
> 
> namespace Com.OneSignal.Core {
>     public class PermissionState {
> ```

Can use most of the contents from Unity:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/Models/PermissionState.cs#L31
___
*[Com.OneSignal.Core/PushSubscriptionState.cs, line 3 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MotmUEr6DRNB5kSGsLr:-MotmUEr6DRNB5kSGsLs:b-aor6vh) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/PushSubscriptionState.cs#L3)):*
> ```Smalltalk
> using System;
> namespace Com.OneSignal.Core {
>     public class PushSubscriptionState {
> ```

Can use contents from Unity:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/Models/PushSubscriptionState.cs#L31
___
*[Samples/Com.OneSignal.Sample.Shared/SharedPush.cs, line 28 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Motr4nBAu4RuVEnikPE:-Motr4nBAu4RuVEnikPF:b57zmzs) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Samples/Com.OneSignal.Sample.Shared/SharedPush.cs#L28)):*
> ```Smalltalk
>          OneSignal.Default.Initialize("77e32082-ea27-42e3-a898-c72e141824ef");
>          //OneSignal.Default.StartInit("b2f7f966-d8cc-11e4-bed1-df8f05be55ba").Settings(new Dictionary<string, bool>() {
>          //   { IOSSettings.kOSSettingsKeyAutoPrompt, false },
> ```

Removed commented out code.
___
*[Samples/Com.OneSignal.Sample.Shared/SharedPush.cs, line 89 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MotsQixAr9LQYX7V5LF:-MotsQiyDJEPYFBAIDs2:b-56x5qm) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Samples/Com.OneSignal.Sample.Shared/SharedPush.cs#L89)):*
> ```Smalltalk
>       }
> 
>       //private static void OneSignalOutcomeEventDemo()
> ```

Address commented out code


<!-- Sent from Reviewable.io -->

2021-11-19 21:49 UTC, jkasten2 requested changes
> Reviewed 4 of 35 files at r1, 33 of 69 files at r2.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 42 unresolved discussions (waiting on @tanaynigam)

___
*[Com.OneSignal.Android/Utilities/NativeConversion.cs, line 19 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Motx1yi79u8QowXOepu:-Motx1yj4STaijAJYLEh:b-f8osji) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Android/Utilities/NativeConversion.cs#L19)):*
> ```Smalltalk
>                 title = notification.Title,
>                 body = notification.Body,
>                 //additionalData = notification.AdditionalData,
> ```

Address additionalData
___
*[Com.OneSignal.Core/Delegate.cs, line 8 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MotxOKY64RDBgqd5i7E:-MotxOKY64RDBgqd5i7F:b-jhu8vh) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/Delegate.cs#L8)):*
> ```Smalltalk
> namespace Com.OneSignal.Core {
> 
>    public delegate void InAppMessageClicked(InAppMessageAction action);
> ```

Aren't these already in `OneSignalSDK.cs`?
___
*[Com.OneSignal.Core/InAppMessage.cs, line 4 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Motxhlv0W6eqWQoydPc:-Motxhlw2moR2ofwP9aT:b-xtvz1m) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/InAppMessage.cs#L4)):*
> ```Smalltalk
> namespace Com.OneSignal.Core {
>     public sealed class InAppMessage {
>         public string id;
> ```

Should be `messageId`, see Unity's:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/Models/InAppMessage.cs#L35
___
*[Com.OneSignal.Core/InAppMessageAction.cs, line 6 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MotxuLq0a5lYbEDP6XC:-MotxuLq0a5lYbEDP6XD:b-53c2ht) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/InAppMessageAction.cs#L6)):*
> ```Smalltalk
> namespace Com.OneSignal.Core {
> 
>    public class InAppMessageAction {
> ```

Update with Unity's properties:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs#L31
___
*[Com.OneSignal.Core/InAppMessageActionUrlType.cs, line 5 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Motz80y67P2n36XSy6Z:-Motz80y67P2n36XSy6_:b-ta0eu7) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/InAppMessageActionUrlType.cs#L5)):*
> ```Smalltalk
> 
> namespace Com.OneSignal.Core {
>    public class InAppMessageActionUrlType {
> ```

Unity simplified `InAppMessageAction` so if we match it then we can delete this class:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs#L31
___
*[Com.OneSignal.Core/InAppMessagePrompt.cs, line 4 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mou-HxrAvUI-ai47ak5:-Mou-HxrAvUI-ai47ak6:bufgbon) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/InAppMessagePrompt.cs#L4)):*
> ```Smalltalk
> 
> namespace Com.OneSignal.Core {
>    public class InAppMessagePrompt {
> ```

We can delete this class if we use Unity's `InAppMessageAction`
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs#L31
___
*[Com.OneSignal.Core/InAppMessageTag.cs, line 5 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mou-iJm8sNgA3P3G44j:-Mou-iJm8sNgA3P3G44k:bygfnkv) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/InAppMessageTag.cs#L5)):*
> ```Smalltalk
> 
> namespace Com.OneSignal.Core {
>     public class InAppMessageTag {
> ```

We can delete this class if we match Unity's `InAppMessageAction`:
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/Models/InAppMessageAction.cs#L31
___
*[Com.OneSignal.Core/LogoutOptions.cs, line 4 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mou-wmB5PvqXdX_wFhw:-Mou-wmB5PvqXdX_wFhx:b5hcp4j) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/LogoutOptions.cs#L4)):*
> ```Smalltalk
> 
> namespace Com.OneSignal.Core {
>     public enum LogoutOptions { Email, SMS, ExternalUserId }
> ```

We can remove this class by updating to what we have in Unity
___
*[Com.OneSignal.Core/Notification.cs, line 16 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mou3dPA5SUAzIrTmG8V:-Mou3dPA5SUAzIrTmG8W:b-nhjr8r) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/Notification.cs#L16)):*
> ```Smalltalk
>       public string title;
>       public string body;
>       //public JSONObject additionalData;
> ```

This should be added as `Dictionary<string, object>`.
It isn't on Unity 3.0.0-beta1 but also left a comment there to follow up.
https://github.com/OneSignal/OneSignal-Unity-SDK/pull/402/files#r753538057
___
*[Com.OneSignal.Core/NotificationActionType.cs, line 4 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mou7oYh2y7Ds90frFhG:-Mou7oYh2y7Ds90frFhH:b-w9vhxk) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/NotificationActionType.cs#L4)):*
> ```Smalltalk
> namespace Com.OneSignal.Core {
>     /// <summary>
>     /// todo - desc
> ```

Address TODO. Can use descriptions from Android as a reference.
https://github.com/OneSignal/OneSignal-Android-SDK/blob/54e4b0fe45bdb7168788d2072a98d573e5a3e599/OneSignalSDK/onesignal/src/main/java/com/onesignal/OSNotificationAction.java#L35
___
*[Com.OneSignal.Core/NotificationReceivedEvent.cs, line 3 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mou8XNR8kjHJKCleRo_:-Mou8XNR8kjHJKCleRoa:b-enjfew) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/NotificationReceivedEvent.cs#L3)):*
> ```Smalltalk
> using System;
> namespace Com.OneSignal.Core {
>    public class NotificationReceivedEvent {
> ```

We can remove this class if we use Unity's `NotificationWillShowDelegate` signature.
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/OneSignal.cs#L57
___
*[Com.OneSignal.Core/SDKDebug.cs, line 5 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mou8iv3B-QTKqbbbism:-Mou8iv3B-QTKqbbbisn:btd8p25) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/af55efedddfea33af9bb9f7369c98c0757afd072/Com.OneSignal.Core/SDKDebug.cs#L5)):*
> ```Smalltalk
> namespace Com.OneSignal.Core {
> 
>     //TODO: Finish Log
> ```

We can use this from Unity
```C#
    /// <summary>
    /// Helper for printing Unity logs formatted to specify they are from this SDK
    /// </summary>
```
https://github.com/OneSignal/OneSignal-Unity-SDK/blob/58a55bf91dfb0d0238725732881974d166700ff1/com.onesignal.unity.core/Runtime/Utilities/SDKDebug.cs#L32-L34
___
*[Com.OneSignal.Core/SubscriptionState.cs, line 3 at r2](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mou908NB1diVs63Hp4v:-Mou908NB1diVs63Hp4w:bg8xwxd) ([raw file] [...]

2021-11-22 04:25 UTC, jkasten2 requested changes
> Reviewed 9 of 9 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 44 unresolved discussions (waiting on @tanaynigam)

___
*[Samples/Com.OneSignal.Sample.iOS/Com.OneSignal.Sample.iOS.csproj, line 79 at r3](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp4rpvc5QxOrpOe0rmg:-Mp4rpvc5QxOrpOe0rmh:b198gbj) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/63f48fc7d0cf4718a611a25bfc005542a522351a/Samples/Com.OneSignal.Sample.iOS/Com.OneSignal.Sample.iOS.csproj#L79)):*
> ```XML
>     <MtouchTlsProvider>Default</MtouchTlsProvider>
>     <MtouchExtraArgs>-v</MtouchExtraArgs>
>     <MtouchFastDev>true</MtouchFastDev>
> ```

MtouchFastDev == incremental builds. It seems to be a Xamarin bug with XCFrameworks getting a link error when targeting a device, the "iPhone" target in Xamarin. Removing it in PR https://github.com/OneSignal/OneSignal-Xamarin-SDK/pull/254.
___
*[Samples/Com.OneSignal.Sample.iOS/ViewController.cs, line 61 at r3](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp4sh9i9JJPHbwgwYwy:-Mp4sh9i9JJPHbwgwYwz:b-2hw4yw) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/63f48fc7d0cf4718a611a25bfc005542a522351a/Samples/Com.OneSignal.Sample.iOS/ViewController.cs#L61)):*
> ```Smalltalk
>       partial void RemoveExternalUserId(UIButton sender)
>       {
>          OneSignal.Default.Logout(Core.LogoutOptions.ExternalUserId);
> ```

Should be `RemoveExternalUserId`, see the latest Unity version for the signature.


<!-- Sent from Reviewable.io -->

2021-11-22 21:49 UTC, jkasten2 requested changes
> Reviewed 2 of 2 files at r6, 2 of 2 files at r7, 5 of 5 files at r8, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 23 unresolved discussions (waiting on @tanaynigam)

___
*[Com.OneSignal.Android/OneSignalImplementation.cs, line 50 at r8](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp8aMy6DJZcGB_eeF78:-Mp8aMy6DJZcGB_eeF79:bxc3er9) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/27c839f691650eee94db1085adeb743c79b9d41c/Com.OneSignal.Android/OneSignalImplementation.cs#L50)):*
> ```Smalltalk
>       }
> 
>       public override void RegisterForPushNotification() {
> ```

Remove `RegisterForPushNotification` this was replaced by `PromptForPushNotificationsWithUserResponse`
___
*[Com.OneSignal.Core/OneSignalSDK.cs, line 151 at r8](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp8alswAwTLqMzi3UGt:-Mp8alswAwTLqMzi3UGu:bn3zcoe) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/27c839f691650eee94db1085adeb743c79b9d41c/Com.OneSignal.Core/OneSignalSDK.cs#L151)):*
> ```Smalltalk
> 
> 
>       ///<summary>
> ```

Remove extra hanging summary comment
___
*[Com.OneSignal.Core/OneSignalSDK.cs, line 154 at r8](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp8b3962J2d3WHeEMQ_:-Mp8b3962J2d3WHeEMQa:bwf5t45) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/27c839f691650eee94db1085adeb743c79b9d41c/Com.OneSignal.Core/OneSignalSDK.cs#L154)):*
> ```Smalltalk
>       ///
>       ///</summary>
>       public abstract void RegisterForPushNotification();
> ```

Remove `RegisterForPushNotification`, this was replaced by `PromptForPushNotificationsWithUserResponse`


<!-- Sent from Reviewable.io -->

2021-11-22 21:51 UTC, jkasten2 requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 24 unresolved discussions (waiting on @tanaynigam)

___
*[Com.OneSignal.Core/Com.OneSignal.Core.csproj, line 6 at r8](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp8c4u68dXWcn-1YZMl:-Mp8c4u68dXWcn-1YZMm:b-t3itzl) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/27c839f691650eee94db1085adeb743c79b9d41c/Com.OneSignal.Core/Com.OneSignal.Core.csproj#L6)):*
> ```XML
>     <TargetFramework>netstandard2.0</TargetFramework>
>     <AssemblyName>Com.OneSignal.Abstractions</AssemblyName>
>     <PackageId>Com.OneSignal.Abstractions</PackageId>
> ```

This `Com.OneSignal.Core.csproj` has a `PackageId` and `assemblyName` of `Com.OneSignal.Abstractions`. Upate this to `Com.OneSignal.Core` to match the file name.
Also this same change will need to be made to the `.nuspec` file.
Lastly search if this was missed anywhere else.


<!-- Sent from Reviewable.io -->

2021-11-23 01:33 UTC, jkasten2 requested changes
Need to update `NotficiationService.cs` yet for `Abstractions` and other changes.

> Reviewed 18 of 18 files at r9, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-:-Mp9PjlvAv3Sheuf4dTt:bc2tjlj)* status: all files reviewed, 18 unresolved discussions (waiting on @tanaynigam)

___
*[Com.OneSignal.nuspec, line 40 at r9](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp9PTM0BcHcLbXmWp5c:-Mp9PTM0BcHcLbXmWp5d:b-e0jbo4) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/a70188bb7cc835fd2232f849e1ab07e261a06c31/Com.OneSignal.nuspec#L40)):*
> ```XML
>         <file src="Com.OneSignal\bin\Release\netstandard2.0\Com.OneSignal.pdb" target="lib\netstandard2.0" />
>         <file src="Com.OneSignal\bin\Release\netstandard2.0\Com.OneSignal.dll" target="lib\netstandard2.0" />
>         <file src="Com.OneSignal.Core\bin\Release\netstandard2.0\Com.OneSignal.Abstractions.pdb" target="lib\netstandard2.0" />
> ```

Need to update `Abstractions` to `Core` here.
___
*[Com.OneSignal.Android/OneSignalCallbacks.cs, line 39 at r9](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp9CGpe8xGlrX2iJh1M:-Mp9CGpe8xGlrX2iJh1N:b-56x5qm) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/a70188bb7cc835fd2232f849e1ab07e261a06c31/Com.OneSignal.Android/OneSignalCallbacks.cs#L39)):*
> ```Smalltalk
>          OneSignalNative.SetNotificationOpenedHandler(new OSNotificationOpenedHandler());
>          OneSignalNative.SetInAppMessageClickHandler(new OSInAppMessageClickHandler());
>          //OneSignalNative.SetInAppMessageLifecycleHandler();
> ```

Address commented out code
___
*[Com.OneSignal.Android/Utilities/NativeConversion.cs, line 129 at r9](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-Mp9PBkC4C79DCZS7dUc:-Mp9PBkC4C79DCZS7dUd:bouxsom) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/a70188bb7cc835fd2232f849e1ab07e261a06c31/Com.OneSignal.Android/Utilities/NativeConversion.cs#L129)):*
> ```Smalltalk
>       }
> 
>       //public static InAppMessageTag InAppMessageTagToNative(Android.OSInAppMessageTag tag) {
> ```

Remove commented out code.


<!-- Sent from Reviewable.io -->

2021-11-23 22:46 UTC, jkasten2 requested changes
> Reviewed 3 of 6 files at r10, 3 of 5 files at r12, 2 of 2 files at r13, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 17 unresolved discussions (waiting on @tanaynigam)

___
*[Com.OneSignal.Android/OneSignalCallbacks.cs, line 32 at r13](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MpDxmg35EVkuVU3cU-m:-MpDxmg35EVkuVU3cU-n:b-bs7syd) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/e18bdf049f6f73987156776b803c31fe82199361/Com.OneSignal.Android/OneSignalCallbacks.cs#L32)):*
> ```Smalltalk
> 
>       public OneSignalImplementation() {
>          if(_instance == null) {
> ```

Should be `if (_instance != null) {`
___
*[Com.OneSignal.Android/OneSignalCallbacks.cs, line 115 at r13](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MpDxyPwAWx_tWCDi_DD:-MpDxyPwAWx_tWCDi_DE:bj14ram) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/e18bdf049f6f73987156776b803c31fe82199361/Com.OneSignal.Android/OneSignalCallbacks.cs#L115)):*
> ```Smalltalk
>       }
> 
>       //private sealed class OSInAppMessageLifeCycleHandler : Android.OSInAppMessageLifecycleHandler {
> ```

Address this comment
___
*[Com.OneSignal.Android/Utilities/NativeConversion.cs, line 65 at r13](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MpDy4ZX3muHK9V3Tw-q:-MpDy4ZX3muHK9V3Tw-r:b8fwr1b) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/e18bdf049f6f73987156776b803c31fe82199361/Com.OneSignal.Android/Utilities/NativeConversion.cs#L65)):*
> ```Smalltalk
> 
>       public static NotificationOpenedResult NotificationOpenedResultToNative(Android.OSNotificationOpenedResult result) {
>          return new NotificationOpenedResult {
> ```

:thumbsup: Nice clean up!


<!-- Sent from Reviewable.io -->

2021-11-23 23:40 UTC, jkasten2 requested changes
> Reviewed 10 of 10 files at r14, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 9 unresolved discussions (waiting on @tanaynigam)

___
*[Samples/Com.OneSignal.Sample.iOS/ViewController.cs, line 45 at r14](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MpE9QsiAC_ANLwzWCbH:-MpE9QsiAC_ANLwzWCbI:bh77hxp) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/3ad43d6f4e301d87f6d6cb6175430fbe5e94ca85/Samples/Com.OneSignal.Sample.iOS/ViewController.cs#L45)):*
> ```Smalltalk
>       //partial void RegisterForPush(UIButton sender)
>       //{
>       //   SharedPush.RegisterIOS();
> ```

Make sure iOS notification prompting works, if this isn't needed remove to do that remove this commented out code.
___
*[Samples/Com.OneSignal.Sample.Shared/SharedPush.cs, line 106 at r14](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MpE9kfzEIdJajRAYhG-:-MpE9kfzEIdJajRAYhG0:bw0b1b5) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/3ad43d6f4e301d87f6d6cb6175430fbe5e94ca85/Samples/Com.OneSignal.Sample.Shared/SharedPush.cs#L106)):*
> ```Smalltalk
>       // No effect on Android, device auto registers without prompting.
>       //public static void RegisterIOS() {
>       //   OneSignal.Default.RegisterForPushNotification();
> ```

This method is in SharedPush, don't we need to keep it for this to work for iOS?


<!-- Sent from Reviewable.io -->

2021-11-23 23:43 UTC, tanaynigam commented
> 



> > Reviewed 10 of 10 files at r14, all commit messages.
> > _[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)_ status: all files reviewed, 9 unresolved discussions (waiting on @tanaynigam)
> 
> _[Samples/Com.OneSignal.Sample.iOS/ViewController.cs, line 45 at r14](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MpE9QsiAC_ANLwzWCbH:-MpE9QsiAC_ANLwzWCbI:bh77hxp) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/3ad43d6f4e301d87f6d6cb6175430fbe5e94ca85/Samples/Com.OneSignal.Sample.iOS/ViewController.cs#L45)):_
> 
> > ```smalltalk
> >       //partial void RegisterForPush(UIButton sender)
> >       //{
> >       //   SharedPush.RegisterIOS();
> > ```
> 
> Make sure iOS notification prompting works, if this isn't needed remove to do that remove this commented out code.
> 
> _[Samples/Com.OneSignal.Sample.Shared/SharedPush.cs, line 106 at r14](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MpE9kfzEIdJajRAYhG-:-MpE9kfzEIdJajRAYhG0:bw0b1b5) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/3ad43d6f4e301d87f6d6cb6175430fbe5e94ca85/Samples/Com.OneSignal.Sample.Shared/SharedPush.cs#L106)):_
> 
> > ```smalltalk
> >       // No effect on Android, device auto registers without prompting.
> >       //public static void RegisterIOS() {
> >       //   OneSignal.Default.RegisterForPushNotification();
> > ```
> 
> This method is in SharedPush, don't we need to keep it for this to work for iOS?

Replacing it with PromptForPushNotification

2021-11-24 00:39 UTC, jkasten2 reviewed
> Reviewed 3 of 3 files at r15, 4 of 4 files at r16, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 2 unresolved discussions (waiting on @tanaynigam)



<!-- Sent from Reviewable.io -->

2021-11-24 00:40 UTC, jkasten2 requested changes
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 3 unresolved discussions (waiting on @tanaynigam)

___
*[Com.OneSignal.iOS/OneSignalImplementation.cs, line 49 at r16](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-MpENec6899WsekrWIUK:-MpENec6899WsekrWIUL:b-jgwn2v) ([raw file](https://github.com/onesignal/onesignal-xamarin-sdk/blob/20438eac92cf9c5539ffda2f2f5307df92938304/Com.OneSignal.iOS/OneSignalImplementation.cs#L49)):*
> ```Smalltalk
>       public override async Task<NotificationPermission> PromptForPushNotificationsWithUserResponse() {
>          BooleanCallbackProxy proxy = new BooleanCallbackProxy();
>          OneSignalNative.PromptForPushNotificationsWithUserResponse(response => proxy.OnResponse(true));
> ```

This shouldn't always use `true`, we need to account if the user declines.


<!-- Sent from Reviewable.io -->

2021-11-30 22:19 UTC, jkasten2 reviewed
> Reviewed 7 of 7 files at r17, 4 of 4 files at r18, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253)* status: all files reviewed, 2 unresolved discussions (waiting on @tanaynigam)



<!-- Sent from Reviewable.io -->

2022-01-31 23:07 UTC, adamschlesinger reviewed
Are we planning to change the package naming + namespacing to be more idiomatic with C#? This would be similar to the change made to Unity.

> *[Reviewable](https://reviewable.io/reviews/onesignal/onesignal-xamarin-sdk/253#-:-MumNx3UEbdRBNuNgnqt:bt7kytw)* status: 71 of 111 files reviewed, 2 unresolved discussions (waiting on @jkasten2 and @tanaynigam)



<!-- Sent from Reviewable.io -->

2022-04-29 21:51 UTC, jkasten2 approved these changes

2022-04-29 21:54 UTC, merged